version: '3.8'

services:
    mongo:
          image: mongo:6
          container_name: mongo
          ports:
            - "27017:27017"
          volumes:
            - mongo-data:/data/db
          restart: always
            
    app-blue:
          build:
            context: ./server
          container_name: suchithrachandrasekaran/todo-app:blue
          environment:
            - MONGO_URI=mongodb://mongo:27017/todos
          expose:
            - "3000"
          networks:
            - app-network
    app-green:
          build:
            context: ./server
          container_name: suchithrachandrasekaran/todo-app:green
          environment:
            - MONGO_URI=mongodb://mongo:27017/todos
          expose:
            - "3000"
          networks:
            - app-network
          deploy:
            replicas: 0  # Will be started when ready
              
    nginx:
          image: nginx:alpine
          container_name: nginx
          ports:
            - "80:80"
          volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
          depends_on:
            - app-blue
          networks:
            - app-network
          restart: always
            
volumes:
  mongo-data:
    
networks:
  app-network:

