name: Blue-Green Deployment

on:
    push:
      branches:
        - main

jobs:
    deploy:
      runs-on: ubuntu-latest
        
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
            
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.4
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
              
        - name: Deploy to EC2 via SSH
          run: |
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
              set -e
            
              echo "Pulling latest blue-green-todo-deploy repo..."
              cd ~/blue-green-todo-deploy || git clone https://github.com/SuchithraChandrasekaran/blue-green-todo-deploy.git && cd blue-green-todo-deploy
              git pull
            
              echo "Starting app-green..."
              docker-compose up -d app-green
            
              echo "Optional: run health check here..."

              echo "Switching traffic to green..."            
              sed -i 's/app-blue:3000/app-green:3000/' nginx.conf
              docker-compose restart nginx
            
              echo "Stopping app-blue..."
              docker-compose stop app-blue
            
              echo "Blue-Green deployment complete!"
            EOF
